exports.games = [
    { id: 0, name: "Морской бой", rate: 0.0 },
    { id: 1, name: "Охота на лис", rate: 0.0 },
    { id: 2, name: "Охота на лис", rate: 0.0 },
    { id: 3, name: "Охота на лис", rate: 0.0 },
    { id: 4, name: "Охота на лис", rate: 0.0 },
    { id: 5, name: "Охота на лис", rate: 0.0 },
    { id: 6, name: "Охота на лис", rate: 0.0 },
    { id: 7, name: "Охота на лис", rate: 0.0 },
    { id: 8, name: "Охота на лис", rate: 0.0 },
    { id: 9, name: "Охота на лис", rate: 0.0 },
    { id: 10, name: "Охота на лис", rate: 0.0 },
    { id: 11, name: "Охота на лис", rate: 0.0 },
    { id: 12, name: "Охота на лис", rate: 0.0 },
    { id: 13, name: "Охота на лис", rate: 0.0 },
    { id: 14, name: "Охота на лис", rate: 0.0 },
  ]