const refXml = document.querySelector("sql");

const tables = document.querySelectorAll("table");
const a = [
	"company",
	"employee",
	"product",
	"category",
	"client",
	"order",
	"price",
	"status",
	"delivery",
	"polygon",
	"polList",
	"delList",
	"arrival",
	"traffic",
	"address",
	"token",
	"remainder",
	"provider",
	"unit",
	"discount",
	"bonus",
	"region",
	"city",
	"dlvTime",
	"num",
	"consumption",
	"place",
	"ordList",
	"courier",
	"rack",
	"cell",
	"role",
	"terms",
	"reward",
	"rewList",
	"arrList",
	"commodity",
	"group",
	"party",
	"box",
	"package",
	"pacStatus",
	"delStatus",
	"doc",
	"payConfig",
	"paySystem",
	"balance",
	"pickup",
	"googlePlay",
	"screen",
	"paw",
	"agent",
	"work",
	"partner",
	"parList",
	"message",
	"entity",
	"town",
	"promo",
	"check",
	"used",
	"img",
	"tariff",
	"tarList",
	"pacList",
	"tarDelivery",
	"tip",
	"tarTip",
	"balEmployee",
	"reduction",
	"payment",
	"card",
	"chosen",
	"bid",
	"bidList",
	"bidOrder",
	"kladr",
	"post",
	"push",
	"property",
	"item",
	"detail",
	"combination",
	"comList",
	"fabric",
	"promotion",
	"proList",
	"proCategory",
	"proProduct",
	"review",
	"cliInfo",
	"favorite",
	"icDict",
	"icSale",
	"calendar",
	"additive",
	"proAdditive",
	"task",
	"celList",
	"comInvoice",
  ];

const ind = {
  box: [{ name: "arrListId" }],
  token: [{ name: "userId" }],
  entity: [
    { name: "name" },
    { name: "inn" },
    { name: "ic.code" },
    { name: "cliInfoId" },
  ],
  address: [{ name: "clientId" }],
  region: [{ name: "companyId" }],
  reduction: [{ name: "companyId" }],
  unit: [{ name: "name" }, { name: "code" }],
  check: [
    { name: "code" },
    { name: "orderId" },
    { name: "paymentId" },
    { name: "url" },
  ],
  city: [{ name: "regionId" }, { name: "type" }],
  rack: [{ name: "companyId" }, { name: "num" }],
  place: [{ name: "qr" }, { name: "companyId" }],
  role: [{ name: "code" }, { name: "employeeId" }],
  price: [{ name: "date" }, { name: "productId" }],
  tarTip: [{ name: "date" }, { name: "companyId" }],
  dlvTime: [{ name: "time" }, { name: "companyId" }],
  bidOrder: [{ name: "bidId" }, { name: "orderId" }],
  bidList: [{ name: "bidId" }, { name: "product.id" }],
  tarDelivery: [{ name: "date" }, { name: "companyId" }],
  googlePlay: [{ name: "title" }, { name: "companyId" }],
  pacList: [{ name: "productId" }, { name: "packageId" }],
  work: [{ name: "date" }, { name: "code" }, { name: "name" }],
  consumption: [
    { name: "owner.id" },
    { name: "trafficId" },
    { name: "mark.code" },
  ],
  paw: [{ name: "date" }, { name: "code" }, { name: "paymentId" }],
  bid: [{ name: "num" }, { name: "partnerId" }, { name: "date" }],
  cell: [{ name: "rackId" }, { name: "num" }],
  party: [{ name: "code" }, { name: "name" }, { name: "companyId" }],
  package: [{ name: "date" }, { name: "qr" }, { name: "arrListId" }],
  partner: [{ name: "date" }, { name: "companyId" }, { name: "off" }],
  post: [{ name: "code" }, { name: "order" }, { name: "companyId" }],
  terms: [{ name: "title" }, { name: "order" }, { name: "companyId" }],
  message: [
    { name: "date" },
    { name: "type" },
    { name: "companyId" },
    { name: "clientId" },
  ],
  tip: [{ name: "date" }, { name: "orderId" }, { name: "employeeId" }],
  screen: [{ name: "img" }, { name: "order" }, { name: "googlePlayId" }],
  town: [{ name: "code" }, { name: "owner.type" }, { name: "owner.id" }],
  discount: [
    { name: "date1" },
    { name: "date2" },
    { name: "productId" },
    { name: "companyId" },
  ],
  tarList: [{ name: "date" }, { name: "tariffId" }, { name: "companyId" }],
  arrList: [{ name: "qr" }, { name: "arrivalId" }, { name: "commodityId" }],
  delList: [{ name: "deliveryId" }, { name: "orderId" }, { name: "order" }],
  courier: [{ name: "employeeId", unique: true }, { name: "isActivated" }],
  polList: [{ name: "polygonId" }, { name: "companyId" }, { name: "order" }],
  card: [{ name: "owner.type" }, { name: "owner.id" }, { name: "companyId" }],
  ordList: [{ name: "orderId" }, { name: "placeId" }, { name: "employeeId" }],
  payConfig: [{ name: "code" }, { name: "paySystemId" }, { name: "companyId" }],

  reward: [
    { name: "code" },
    { name: "name" },
    { name: "unique" },
  ],
  doc: [
    { name: "date" },
    { name: "name" },
    { name: "type" },
    { name: "companyId" },
  ],
  num: [
    { name: "year" },
    { name: "type" },
    { name: "guid" },
    { name: "companyId" },
  ],
  commodity: [
    { name: "code" },
    { name: "name" },
    { name: "qr" },
    { name: "groupId" },
  ],
  img: [
    { name: "name" },
    { name: "owner.id" },
    { name: "owner.type" },
  ],
  used: [
    { name: "date" },
    { name: "clientId" },
    { name: "promoId" },
    { name: "orderId" },
  ],
  fabric: [
    { name: "trafficId" },
    { name: "employeeId" },
    { name: "date1" },
    { name: "date2" },
  ],
  review: [
    { name: "date" },
    { name: "rating" },
    { name: "productId" },
    { name: "clientId" },
  ],
  bonus: [
    { name: "date" },
    { name: "orderId" },
    { name: "rewardId" },
    { name: "clientId" },
    { name: "companyId" },
  ],
  chosen: [
    { name: "date" },
    { name: "productId" },
    { name: "clientId" },
    { name: "companyId" },
  ],
  pacStatus: [
    { name: "date" },
    { name: "code" },
    { name: "packageId" },
    { name: "employeeId" },
  ],
  delStatus: [
    { name: "date" },
    { name: "code" },
    { name: "employeeId" },
    { name: "deliveryId" },
  ],
  client: [
    { name: "date" },
    { name: "phone", unique: true },
  ], 
  balEmployee: [
    { name: "date" },
    { name: "type" },
    { name: "deliveryId" },
    { name: "employeeId" },
  ],
  parList: [
    { name: "order" },
    { name: "productId" },
    { name: "categoryId" },
    { name: "partnerId" },
    { name: "off" },
  ],
  payment: [
    { name: "type" },
    { name: "owner.type" },
    { name: "owner.id" },
    { name: "payConfig.id" },
  ],
  category: [
    { name: "name" },
    { name: "img" },
    { name: "order" },
    { name: "off" },
    { name: "ic.code" },
    { name: "parent" },
    { name: "companyId" },
  ],
  rewList: [
    { name: "date1" },
    { name: "date2" },
    { name: "order" },
    { name: "rewardId" },
    { name: "companyId" },
  ],
  arrival: [
    { name: "date" },
    { name: "doc.num" },
    { name: "code" },
    { name: "qr" },
    { name: "closed" },
    { name: "companyId" },
    { name: "providerId" },
  ],
  employee: [
    { name: "date" },
    { name: "login", unique: true },
    { name: "phone" },
    { name: "companyId" },
    { name: "isActivated" },
  ],
  balance: [
    { name: "date" },
    { name: "type" },
    { name: "owner.type" },
    { name: "owner.id" },
    { name: "companyId" },
  ],
  status: [
    { name: "date" },
    { name: "code" },
    { name: "employeeId" },
    { name: "orderId" },
    { name: "companyId" },
  ],
  traffic: [
    { name: "date" },
    { name: "closed" },
    { name: "productId" },
    { name: "partnerId" },
    { name: "orderId" },
  ],
  remainder: [
    { name: "date" },
    { name: "closed" },
    { name: "productId" },
    { name: "owner.id" },
    { name: "owner.type" },
  ],
  provider: [
    { name: "code" },
    { name: "inn" },
    { name: "kpp" },
    { name: "ogrn" },
    { name: "phone" },
    { name: "email" },
    { name: "partyId" },
  ],
  tariff: [
    { name: "name" },
    { name: "subscription" },
    { name: "write" },
    { name: "sms" },
    { name: "month" },
    { name: "off" },
  ],
  delivery: [
    { name: "date" },
    { name: "num" },
    { name: "create" },
    { name: "closed" },
    { name: "employeeId" },
  ],
  pickup: [
    { name: "geo.type" },
    { name: "geo.coordinates" },
    { name: "time.beg" },
    { name: "time.end" },
    { name: "schedule" },
    { name: "companyId" },
  ],
  company: [
    { name: "date" },
    { name: "code", unique: true },
    { name: "name" },
    { name: "inn" },
    { name: "delivery.type.courier" },
    { name: "delivery.type.picker" },
    { name: "delivery.type.post" },
    { name: "payment.payConfigId" },
    { name: "agentId" }
  ],
  agent: [
    { name: "date" },
    { name: "code" },
    { name: "name.first" },
    { name: "name.last" },
    { name: "name.middle" },
    { name: "phone" },
    { name: "closed" },
  ],
  promo: [
    { name: "date1" },
    { name: "date2" },
    { name: "price" },
    { name: "one" },
    { name: "new" },
    { name: "min" },
    { name: "closed" },
    { name: "owner.type" },
    { name: "owner.id" },
    { name: "companyId" },
  ],
  order: [
    { name: "date" },
    { name: "num" },
    { name: "delivery.date" },
    { name: "ic.code" },
    { name: "closed" },
    { name: "entity.id" },
    { name: "owner.type" },
    { name: "owner.id" },
    { name: "clientId" },
    { name: "companyId" },
  ],
  product: [
    { name: "name" },
    { name: "unit" },
    { name: "mfr" },
    { name: "qr" },
    { name: "code" },
    { name: "order" },
    { name: "ready.type" },
    { name: "ready.day" },
    { name: "off" },
    { name: "categoryId" },
  ],
  cliInfo: [
    { name: "date" },
    { name: "name" },
    { name: "born" },
    { name: "email" },
    { name: "invited.clientId" },
    { name: "invited.orderId" },
    { name: "clientId" },
    { name: "companyId" },
  ],
  icDict: [
    { name: "entity" },
    { name: "name" },
    { name: "code" },
    { name: "companyId" },
  ],
  icSale: [
    { name: "date" },
    { name: "code" },
    { name: "closed" },
    { name: "commodityId" },
  ],

  combination: [{ name: "productId" }, { name: "exclude.on" }],
  comList: [{ name: "itemId" }, { name: "combinationId" }],
  property: [{ name: "name" }, { name: "type" }, { name: "productId" }],
  item: [{ name: "name" }, { name: "propertyId" }, { name: "order" }],
  // new
  polygon: [{ name: "name" },{ name: "geo.type" },{ name: "geo.coordinates" }],
  group: [{ name: "code" },{ name: "name" },{ name: "parent" },{ name: "companyId" }],
  paySystem: [{ name: "name" },{ name: "config.code" }],
  push: [{ name: "owner.type" },{ name: "owner.id" }, { name: "companyId" }],
  favorite: [{ name: "productId" },{ name: "clientId" },{ name: "companyId" }],
  detail: [{ name: "owner.id" }, { name: "itemId" }],
  calendar: [{ name: "date" }, { name: "companyId" }],
  additive: [{ name: "name" }, { name: "companyId" }],
  proAdditive: [{ name: "additiveId" }, { name: "productId" }],
  task: [{ name: "name" }, { name: "companyId" }],
  celList: [{ name: "owner.type" },{ name: "owner.id" },{ name: "cellId" }],
  promotion: [{ name: "name" },{ name: "order" },{ name: "companyId" }],
  proCategory: [{ name: "order" },{ name: "categoryId" },{ name: "promotionId" }],
  proProduct: [{ name: "order" },{ name: "productId" },{ name: "promotionId" }],
  proList: [{ name: "order" },{ name: "promotionId" }],
  comInvoice: [{ name: "phone" },{ name: "companyId" }]
//     kladr: [{ name: "name" }]
};

// массив имен коллекций из xml
// const coll = [];
// for (let i = 0; i < tables.length; i++) {
//   const table = tables[i].attributes.name.nodeValue;
//   coll.push(table);
// }
// console.log("Исходный", coll, a);

// // массив отличий и сходств
// const difC = coll.filter((val, idx) => !a.includes(val));
// const difA = a.filter((val, idx) => !coll.includes(val));
// console.log("отличия", difC, difA);

// const difCr = coll.filter((val, idx) => a.includes(val));
// const difAr = a.filter((val, idx) => coll.includes(val));
// console.log("сходства", difCr, difAr);

// // удалить и найти дупликаты
// const cl = [];
// for (let i = 0; i < a.length; i++) {
//   if (!cl.includes(a[i])) {
//     cl.push(a[i]);
//   } else {
//     console.log("duplex", a[i]);
//   }
// }

// // массив имен коллекций из ind
// const rInd = Object.keys(ind);
// const difInd = coll.filter((val, idx) => !rInd.includes(val));
// console.log("Ind", rInd, "Different", difInd);

const l1 = [2,4,3]
const l2 = [5,6,4]

var addTwoNumbers = function(l1, l2) {
    return String(Number(l1.join('')) + Number(l2.join(''))).split('').reverse()
    
    
};

console.log(addTwoNumbers(l1,l2))